version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_TYPE: 'postgres'
      MB_DB_DBNAME: 'metabase'
      MB_DB_PORT: 5432
      MB_DB_USER: 'metabase'
      MB_DB_HOST: 'postgres'
      MB_DB_PASS: 'metabase'
    ports:
      - '3000:3000'
    networks:
      - my-network

  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase
    #command: tail -f /etc/fstab
    volumes:
      - ./pg:/var/lib/postgresql/data
	networks:
	  - my-network

